package com.github.sergueik.selenium;

/**
 * Copyright 2022 Serguei Kouzmine
 */

import static org.hamcrest.CoreMatchers.notNullValue;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.greaterThan;

import java.util.List;
import java.util.Optional;

import org.junit.Test;
import org.openqa.selenium.devtools.v112.browser.Browser;
import org.openqa.selenium.devtools.v112.browser.model.Histogram;

/**
 * 
 * Selected test scenarios for Selenium 4 Chrome Developer Tools bridge
 * https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-getHistograms
 * https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-getHistogram
z* @author: Serguei Kouzmine (kouzmine_serguei@yahoo.com)
 */

public class BrowserHistogramDevToolsTest extends BaseDevToolsTest {

	private final static String url = "https://en.wikipedia.org/wiki/Main_Page";

	private static List<Histogram> results;
	private static Histogram result;
	private static boolean debug = false;

	@Test
	public void test() {
		// Arrange
		driver.get(url);
		// Act
		List<Histogram> results = chromeDevTools
				.send(Browser.getHistograms(Optional.empty(), Optional.of(false)));
		// Assert
		assertThat(results, notNullValue());
		assertThat(results.size(), greaterThan(0));
		result = results.get(0);
		String name = result.getName();
		// NOTE: almost a 1000 histograms (copy saved in the comment below)
		if (debug)
			results.stream().map(o -> o.getName()).forEach(System.err::println);

		assertThat(name, notNullValue());
		result = chromeDevTools
				.send(Browser.getHistogram(name, Optional.of(false)));

	}

}
/*
	API.StorageAccess.AllowedRequests2
	Accessibility.CaptionSettingsLoadedFromPrefs
	Accessibility.LiveCaption
	Accessibility.LiveCaption.FeatureEnabled
	AppBanners.InstallableStatusCode
	Autocomplete.Cleanup
	AutocompleteActionPredictor.Action
	Autofill.Address.IsEnabled.PageLoad
	Autofill.Address.IsEnabled.PageLoad.SignedOut
	Autofill.Address.IsEnabled.Startup
	Autofill.CreditCard.IsEnabled.PageLoad
	Autofill.CreditCard.IsEnabled.PageLoad.SignedOut
	Autofill.CreditCard.IsEnabled.Startup
	Autofill.FormCacheSize
	Autofill.Funnel.ParsedAsType.Address
	Autofill.Funnel.ParsedAsType.CreditCard
	Autofill.GetUnownedFormFieldsDuration
	Autofill.IsEnabled.PageLoad
	Autofill.IsEnabled.PageLoad.SignedOut
	Autofill.IsEnabled.Startup
	Autofill.Offer.StoredOfferCount
	Autofill.StoredCreditCardCount
	Autofill.StoredCreditCardCount.Local
	Autofill.StoredCreditCardCount.Local.WithNickname
	Autofill.StoredCreditCardCount.Server
	Autofill.StoredCreditCardCount.Server.Masked
	Autofill.StoredCreditCardCount.Server.Masked.WithNickname
	Autofill.StoredCreditCardCount.Server.Unmasked
	Autofill.StoredCreditCardCount.Server.WithCardArtImage
	Autofill.StoredCreditCardCount.Server.WithVirtualCardMetadata
	Autofill.StoredProfileCount
	BackgroundFetch.IncompleteFetchesOnStartup
	BackgroundFetch.Storage.CleanupTask
	BackgroundFetch.Storage.GetInitializationDataTask
	BackgroundMode.BackgroundApplicationsCount
	BackgroundMode.OnStartup.AutoLaunchState
	BackgroundMode.OnStartup.IsBackgroundModePrefEnabled
	Blink.AnchorElementMetricsIntersectionObserver.UpdateTime.AggregatedPreFCP
	Blink.AnchorElementMetricsIntersectionObserver.UpdateTime.PostFCP
	Blink.AnchorElementMetricsIntersectionObserver.UpdateTime.PreFCP
	Blink.Animate.UpdateTime.AggregatedPreFCP
	Blink.Animate.UpdateTime.PostFCP
	Blink.Animate.UpdateTime.PreFCP
	Blink.CompositingCommit.UpdateTime.AggregatedPreFCP
	Blink.CompositingCommit.UpdateTime.PostFCP
	Blink.CompositingCommit.UpdateTime.PreFCP
	Blink.CompositingInputs.UpdateTime.AggregatedPreFCP
	Blink.CompositingInputs.UpdateTime.PostFCP
	Blink.CompositingInputs.UpdateTime.PreFCP
	Blink.ContentDocumentUpdate.UpdateTime.AggregatedPreFCP
	Blink.ContentDocumentUpdate.UpdateTime.PostFCP
	Blink.ContentDocumentUpdate.UpdateTime.PreFCP
	Blink.DisplayLockIntersectionObserver.UpdateTime.AggregatedPreFCP
	Blink.DisplayLockIntersectionObserver.UpdateTime.PostFCP
	Blink.DisplayLockIntersectionObserver.UpdateTime.PreFCP
	Blink.EffectiveZoom
	Blink.Fonts.FontFamilyMatchAttempts.System
	Blink.Fonts.FontMatchAttempts.System
	Blink.ForcedStyleAndLayout.UpdateTime.AggregatedPreFCP
	Blink.ForcedStyleAndLayout.UpdateTime.PostFCP
	Blink.ForcedStyleAndLayout.UpdateTime.PreFCP
	Blink.HandleInputEvents.UpdateTime.AggregatedPreFCP
	Blink.HandleInputEvents.UpdateTime.PostFCP
	Blink.HandleInputEvents.UpdateTime.PreFCP
	Blink.HitTestDocumentUpdate.UpdateTime.AggregatedPreFCP
	Blink.HitTestDocumentUpdate.UpdateTime.PostFCP
	Blink.HitTestDocumentUpdate.UpdateTime.PreFCP
	Blink.ImplCompositorCommit.UpdateTime.AggregatedPreFCP
	Blink.ImplCompositorCommit.UpdateTime.PostFCP
	Blink.ImplCompositorCommit.UpdateTime.PreFCP
	Blink.IntersectionObservation.UpdateTime.AggregatedPreFCP
	Blink.IntersectionObservation.UpdateTime.PostFCP
	Blink.IntersectionObservation.UpdateTime.PreFCP
	Blink.IntersectionObservationInternalCount.UpdateTime.AggregatedPreFCP
	Blink.IntersectionObservationInternalCount.UpdateTime.PostFCP
	Blink.IntersectionObservationInternalCount.UpdateTime.PreFCP
	Blink.IntersectionObservationJavascriptCount.UpdateTime.AggregatedPreFCP
	Blink.IntersectionObservationJavascriptCount.UpdateTime.PostFCP
	Blink.IntersectionObservationJavascriptCount.UpdateTime.PreFCP
	Blink.JavascriptDocumentUpdate.UpdateTime.AggregatedPreFCP
	Blink.JavascriptDocumentUpdate.UpdateTime.PostFCP
	Blink.JavascriptDocumentUpdate.UpdateTime.PreFCP
	Blink.JavascriptIntersectionObserver.UpdateTime.AggregatedPreFCP
	Blink.JavascriptIntersectionObserver.UpdateTime.PostFCP
	Blink.JavascriptIntersectionObserver.UpdateTime.PreFCP
	Blink.Layout.UpdateTime.AggregatedPreFCP
	Blink.Layout.UpdateTime.PostFCP
	Blink.Layout.UpdateTime.PreFCP
	Blink.LazyLoadIntersectionObserver.UpdateTime.AggregatedPreFCP
	Blink.LazyLoadIntersectionObserver.UpdateTime.PostFCP
	Blink.LazyLoadIntersectionObserver.UpdateTime.PreFCP
	Blink.MainFrame.UpdateTime.AggregatedPreFCP
	Blink.MainFrame.UpdateTime.PostFCP
	Blink.MainFrame.UpdateTime.PreFCP
	Blink.MediaIntersectionObserver.UpdateTime.AggregatedPreFCP
	Blink.MediaIntersectionObserver.UpdateTime.PostFCP
	Blink.MediaIntersectionObserver.UpdateTime.PreFCP
	Blink.Paint.UpdateTime.AggregatedPreFCP
	Blink.Paint.UpdateTime.PostFCP
	Blink.Paint.UpdateTime.PreFCP
	Blink.ParseStyleSheet.UpdateTime.AggregatedPreFCP
	Blink.ParseStyleSheet.UpdateTime.PostFCP
	Blink.ParseStyleSheet.UpdateTime.PreFCP
	Blink.Plugin.UpdateTime
	Blink.PrePaint.UpdateTime.AggregatedPreFCP
	Blink.PrePaint.UpdateTime.PostFCP
	Blink.PrePaint.UpdateTime.PreFCP
	Blink.Script.AsyncScriptCount
	Blink.ScrollDocumentUpdate.UpdateTime.AggregatedPreFCP
	Blink.ScrollDocumentUpdate.UpdateTime.PostFCP
	Blink.ScrollDocumentUpdate.UpdateTime.PreFCP
	Blink.ServiceDocumentUpdate.UpdateTime.AggregatedPreFCP
	Blink.ServiceDocumentUpdate.UpdateTime.PostFCP
	Blink.ServiceDocumentUpdate.UpdateTime.PreFCP
	Blink.Style.UpdateTime.AggregatedPreFCP
	Blink.Style.UpdateTime.PostFCP
	Blink.Style.UpdateTime.PreFCP
	Blink.UpdateViewportIntersection.UpdateTime.AggregatedPreFCP
	Blink.UpdateViewportIntersection.UpdateTime.PostFCP
	Blink.UpdateViewportIntersection.UpdateTime.PreFCP
	Blink.UseCounter.AnimatedCSSProperties
	Blink.UseCounter.CSSProperties
	Blink.UseCounter.Features
	Blink.UseCounter.MainFrame.Features
	Blink.UseCounter.PermissionsPolicy.Header2
	Blink.UserDrivenDocumentUpdate.UpdateTime.AggregatedPreFCP
	Blink.UserDrivenDocumentUpdate.UpdateTime.PostFCP
	Blink.UserDrivenDocumentUpdate.UpdateTime.PreFCP
	Blink.WaitForCommit.UpdateTime.AggregatedPreFCP
	Blink.WaitForCommit.UpdateTime.PostFCP
	Blink.WaitForCommit.UpdateTime.PreFCP
	Bookmarks.Count.OnProfileLoad
	Bookmarks.Count.OnProfileLoad.UniqueUrl
	Bookmarks.Count.OnProfileLoad.UniqueUrlAndTitle
	Bookmarks.Count.OnProfileLoad.UniqueUrlAndTitleAndParent
	BrowserRenderProcessHost.SpareProcessMaybeTakeAction
	BrowserSwitcher.ExternalGreylistSize
	BrowserSwitcher.ExternalSitelistSize
	BrowserSwitcher.IeemSitelistSize
	CertificateType2.BR.Intermediate.RSA
	CertificateType2.BR.Leaf.ECDSA
	CertificateType2.BR.Root.RSA
	ChildProcess.Launched.UtilityProcessHash
	Chrome.CommandLineDatDirCount
	Chrome.ProcessSingleton.NotifyResult
	Chrome.ProcessSingleton.TimeToCreate
	ChromeElf.Beacon.RetryAttemptsBeforeSuccess
	ChromeElf.Beacon.SetupStatus
	ChromeElf.ExtensionPoint.EnableState
	ClientHints.CriticalCHRestart
	ClientHints.FetchLatency
	ClientHints.StoreLatency
	ClientHints.UpdateEventCount
	ClientHints.UpdateSize
	Compositing.Browser.GPUMemoryForTilingsInKb
	Compositing.Browser.LayerTreeImpl.CalculateDrawPropertiesUs
	Compositing.Browser.LayersUpdateTime
	Compositing.Browser.NumActiveLayers
	Compositing.Browser.NumActivePictureLayers
	Compositing.Browser.NumRenderSurfaces
	Compositing.DidMainThreadBlockDuringCommit
	Compositing.MainThreadBlockedDuringCommitTime
	Compositing.Renderer.GPUMemoryForTilingsInKb
	Compositing.Renderer.LayerTreeImpl.CalculateDrawPropertiesUs
	Compositing.Renderer.LayerUpdateSkippedDueToBackface
	Compositing.Renderer.LayersUpdateTime
	Compositing.Renderer.NumActiveLayers
	Compositing.Renderer.NumActivePictureLayers
	Compositing.Renderer.NumRenderSurfaces
	Compositing.ResourcePoolMemoryUsage.Browser
	CompositorLatency.Activation
	CompositorLatency.BeginImplFrameToSendBeginMainFrame
	CompositorLatency.Commit
	CompositorLatency.CompositorOnlyFrame.BeginImplFrameToFinishImpl
	CompositorLatency.CompositorOnlyFrame.ImplFrameDoneToSubmitCompositorFrame
	CompositorLatency.CompositorOnlyFrame.SubmitCompositorFrameToPresentationCompositorFrame
	CompositorLatency.CompositorOnlyFrame.TotalLatency
	CompositorLatency.DroppedFrame.BeginImplFrameToSendBeginMainFrame
	CompositorLatency.DroppedFrame.TotalLatency
	CompositorLatency.EndActivateToSubmitCompositorFrame
	CompositorLatency.EndCommitToActivation
	CompositorLatency.MissedDeadlineFrame.Activation
	CompositorLatency.MissedDeadlineFrame.BeginImplFrameToSendBeginMainFrame
	CompositorLatency.MissedDeadlineFrame.Commit
	CompositorLatency.MissedDeadlineFrame.EndActivateToSubmitCompositorFrame
	CompositorLatency.MissedDeadlineFrame.EndCommitToActivation
	CompositorLatency.MissedDeadlineFrame.SendBeginMainFrameToCommit
	CompositorLatency.MissedDeadlineFrame.SendBeginMainFrameToCommit.Animate
	CompositorLatency.MissedDeadlineFrame.SendBeginMainFrameToCommit.BeginMainSentToStarted
	CompositorLatency.MissedDeadlineFrame.SendBeginMainFrameToCommit.CompositeCommit
	CompositorLatency.MissedDeadlineFrame.SendBeginMainFrameToCommit.CompositingInputs
	CompositorLatency.MissedDeadlineFrame.SendBeginMainFrameToCommit.HandleInputEvents
	CompositorLatency.MissedDeadlineFrame.SendBeginMainFrameToCommit.LayoutUpdate
	CompositorLatency.MissedDeadlineFrame.SendBeginMainFrameToCommit.Paint
	CompositorLatency.MissedDeadlineFrame.SendBeginMainFrameToCommit.Prepaint
	CompositorLatency.MissedDeadlineFrame.SendBeginMainFrameToCommit.StyleUpdate
	CompositorLatency.MissedDeadlineFrame.SendBeginMainFrameToCommit.UpdateLayers
	CompositorLatency.MissedDeadlineFrame.SubmitCompositorFrameToPresentationCompositorFrame
	CompositorLatency.MissedDeadlineFrame.TotalLatency
	CompositorLatency.SendBeginMainFrameToCommit
	CompositorLatency.SendBeginMainFrameToCommit.Animate
	CompositorLatency.SendBeginMainFrameToCommit.BeginMainSentToStarted
	CompositorLatency.SendBeginMainFrameToCommit.CompositeCommit
	CompositorLatency.SendBeginMainFrameToCommit.CompositingInputs
	CompositorLatency.SendBeginMainFrameToCommit.HandleInputEvents
	CompositorLatency.SendBeginMainFrameToCommit.LayoutUpdate
	CompositorLatency.SendBeginMainFrameToCommit.Paint
	CompositorLatency.SendBeginMainFrameToCommit.Prepaint
	CompositorLatency.SendBeginMainFrameToCommit.StyleUpdate
	CompositorLatency.SendBeginMainFrameToCommit.UpdateLayers
	CompositorLatency.SubmitCompositorFrameToPresentationCompositorFrame
	CompositorLatency.TotalLatency
	CompositorLatency.Type
	CompositorLatency.Type.NoInteraction
	ContentSettings.DefaultAutoplaySetting
	ContentSettings.DefaultCookiesSetting
	ContentSettings.DefaultIdleDetectionSetting
	ContentSettings.DefaultImagesSetting
	ContentSettings.DefaultJavaScriptSetting
	ContentSettings.DefaultLocationSetting
	ContentSettings.DefaultMIDISysExSetting
	ContentSettings.DefaultMediaStreamCameraSetting
	ContentSettings.DefaultMediaStreamMicSetting
	ContentSettings.DefaultNotificationsSetting
	ContentSettings.DefaultPopupsSetting
	ContentSettings.DefaultSoundSetting
	ContentSettings.DefaultSubresourceFilterSetting
	ContentSettings.DefaultUsbGuardSetting
	ContentSettings.DefaultWebBluetoothGuardSetting
	ContentSettings.Exceptions.accessibility-events
	ContentSettings.Exceptions.app-banner
	ContentSettings.Exceptions.ar
	ContentSettings.Exceptions.auto-select-certificate
	ContentSettings.Exceptions.automatic-downloads
	ContentSettings.Exceptions.autoplay
	ContentSettings.Exceptions.background-sync
	ContentSettings.Exceptions.bluetooth-chooser-data
	ContentSettings.Exceptions.bluetooth-guard
	ContentSettings.Exceptions.bluetooth-scanning
	ContentSettings.Exceptions.camera-pan-tilt-zoom
	ContentSettings.Exceptions.client-hints
	ContentSettings.Exceptions.clipboard
	ContentSettings.Exceptions.cookies
	ContentSettings.Exceptions.cookies.Allow
	ContentSettings.Exceptions.cookies.AllowThirdParty
	ContentSettings.Exceptions.cookies.Block
	ContentSettings.Exceptions.cookies.SessionOnly
	ContentSettings.Exceptions.durable-storage
	ContentSettings.Exceptions.file-system-access-chooser-data
	ContentSettings.Exceptions.file-system-last-picked-directory
	ContentSettings.Exceptions.file-system-read-guard
	ContentSettings.Exceptions.file-system-write-guard
	ContentSettings.Exceptions.font-access
	ContentSettings.Exceptions.formfill-metadata
	ContentSettings.Exceptions.geolocation
	ContentSettings.Exceptions.hid-chooser-data
	ContentSettings.Exceptions.hid-guard
	ContentSettings.Exceptions.http-allowed
	ContentSettings.Exceptions.idle-detection
	ContentSettings.Exceptions.images
	ContentSettings.Exceptions.important-site-info
	ContentSettings.Exceptions.insecure-private-network
	ContentSettings.Exceptions.installed-web-app-metadata
	ContentSettings.Exceptions.intent-picker-auto-display
	ContentSettings.Exceptions.javascript
	ContentSettings.Exceptions.javascript-jit
	ContentSettings.Exceptions.legacy-cookie-access
	ContentSettings.Exceptions.media-engagement
	ContentSettings.Exceptions.media-stream-camera
	ContentSettings.Exceptions.media-stream-mic
	ContentSettings.Exceptions.midi-sysex
	ContentSettings.Exceptions.mixed-script
	ContentSettings.Exceptions.nfc-devices
	ContentSettings.Exceptions.notifications
	ContentSettings.Exceptions.password-protection
	ContentSettings.Exceptions.payment-handler
	ContentSettings.Exceptions.permission-autoblocking-data
	ContentSettings.Exceptions.permission-autorevocation-data
	ContentSettings.Exceptions.popups
	ContentSettings.Exceptions.popups.Allow
	ContentSettings.Exceptions.popups.Block
	ContentSettings.Exceptions.ppapi-broker
	ContentSettings.Exceptions.protected-media-identifier
	ContentSettings.Exceptions.protocol-handler
	ContentSettings.Exceptions.safe-browsing-url-check-data
	ContentSettings.Exceptions.sensors
	ContentSettings.Exceptions.serial-chooser-data
	ContentSettings.Exceptions.serial-guard
	ContentSettings.Exceptions.site-engagement
	ContentSettings.Exceptions.sound
	ContentSettings.Exceptions.ssl-cert-decisions
	ContentSettings.Exceptions.storage-access
	ContentSettings.Exceptions.subresource-filter
	ContentSettings.Exceptions.subresource-filter-data
	ContentSettings.Exceptions.subresource-filter.Allow
	ContentSettings.Exceptions.subresource-filter.Block
	ContentSettings.Exceptions.usb-chooser-data
	ContentSettings.Exceptions.usb-guard
	ContentSettings.Exceptions.vr
	ContentSettings.Exceptions.webid-active-session
	ContentSettings.Exceptions.webid-request
	ContentSettings.Exceptions.webid-share
	ContentSettings.Exceptions.window-placement
	ContentSettings.NumberOfExceptions
	ContentSettings.Plugins
	ContentSettings.Popups.StrongBlockerActions
	Conversions.RegisteredConversionsPerPage
	Conversions.RegisteredImpressionsPerPage
	Cookie.FromStorageWithValidLength
	DevTools.CDPCommandFromDevTools
	DevTools.CDPCommandFromRemoteDebugger
	DirectWrite.Fonts.Content.FindFamilyTime
	DirectWrite.Fonts.Content.GetFamilyCountTime
	DirectWrite.Fonts.Content.GetFontFilesTime
	DirectWrite.Fonts.Content.InitializeTime
	DirectWrite.Fonts.Gfx.InitializeLoopCount
	DirectWrite.Fonts.Gfx.InitializeTime
	DirectWrite.Fonts.Proxy.LastResortFontCount
	DirectWrite.Fonts.Proxy.LastResortFontFileCount
	DirectWrite.Fonts.Proxy.LoaderType
	Discarding.DailyDiscards.External
	Discarding.DailyDiscards.Urgent
	Discarding.DailyReloads.External
	Discarding.DailyReloads.Urgent
	DiskCache.4.Error
	DiskCache.CreateBlock
	DiskCache.GetFileForNewBlock
	Document.BeforeUnloadDialog
	DocumentEventTiming.PageHideDuration
	DocumentEventTiming.PageVibilityHiddenDuration
	DocumentEventTiming.UnloadDuration
	Enterprise.ManagementAuthorityThrustworthyness.Cache.ValueChange
	Enterprise.PolicyLoadStatus
	EnterpriseCheck.InvalidPoliciesDetected
	Event.AggregatedLatency.Renderer2
	Event.AsyncTargeting.AsyncClientDepth
	Event.Latency.HitTest
	Event.PageShow.Persisted
	Event.VizHitTest.HitTestDataIsEqualAccuracy
	ExtensionToolbarModel.BrowserActionsCount
	Extensions.AppLocation
	Extensions.CheckForExternalUpdatesTime
	Extensions.ChromeExtensionsClientInitTime2
	Extensions.ContentVerification.ComputedHashesReadResult
	Extensions.ContentVerification.ReadContentHashTime
	Extensions.CorruptExtensionTotalDisables
	Extensions.Database.Database.Restore.Scripts
	Extensions.Database.Database.Restore.State
	Extensions.Database.Open.Scripts
	Extensions.Database.Open.State
	Extensions.Database.Value.Restore.Scripts
	Extensions.Database.Value.Restore.State
	Extensions.DidCreateScriptContext_Unspecified
	Extensions.DidCreateScriptContext_WebPage
	Extensions.Disabled
	Extensions.DisabledForPermissions
	Extensions.EventlessEventPages
	Extensions.ExtensionLocation
	Extensions.ExtensionRootPathLength
	Extensions.FeatureProviderStaticInitTime
	Extensions.HomepageOverrides
	Extensions.InitPrefGetExtensionsTime
	Extensions.InjectEnd_ScriptCount
	Extensions.InjectIdle_ScriptCount
	Extensions.InjectStart_CssCount
	Extensions.InjectStart_ScriptCount
	Extensions.LoadAll
	Extensions.LoadAllComponentTime
	Extensions.LoadAllTime2
	Extensions.LoadApp
	Extensions.LoadAppExternal
	Extensions.LoadAppUser
	Extensions.LoadBrowserAction
	Extensions.LoadExtension
	Extensions.LoadExtensionExternal
	Extensions.LoadExtensionUser
	Extensions.LoadHostedApp
	Extensions.LoadNoExtensionAction
	Extensions.LoadOffStoreItems
	Extensions.LoadPackagedApp
	Extensions.LoadPlatformApp
	Extensions.LoadTheme
	Extensions.LoadUserScript
	Extensions.Management_Refresh
	Extensions.ManifestReloadNeedsRelocalization
	Extensions.ManifestReloadNotNeeded
	Extensions.ManifestReloadUnpackedDir
	Extensions.NewTabPageOverrides
	Extensions.NonWebStoreNewTabPageOverrides
	Extensions.NonWebstoreLocation
	Extensions.NotAllowlistedDisabled
	Extensions.NotAllowlistedEnabled
	Extensions.ProcessManagerStartupHostsTime2
	Extensions.SearchEngineOverrides
	Extensions.StartupPagesOverrides
	Extensions.UpdateOnLoad
	Extensions.WebRequestBlockingCount
	Extensions.WebRequestCount
	GPU.AcceleratedSurfaceRefreshRate
	GPU.BlocklistFeatureTestResults.Accelerated2dCanvas
	GPU.BlocklistFeatureTestResults.GpuCompositing
	GPU.BlocklistFeatureTestResults.GpuRasterization
	GPU.BlocklistFeatureTestResults.Webgl
	GPU.BlocklistFeatureTestResults.Webgl2
	GPU.BlocklistTestResultsPerEntry
	GPU.CanvasOopRaster.OopRasterAndGpuAcceleration
	GPU.DriverBugTestResultsPerEntry
	GPU.GPUInitializationTime.V3
	GPU.GPUProcessInitialized
	GPU.GPUProcessLaunchTime
	GPU.GpuCount
	GPU.HardwareAccelerationModeEnabled
	GPU.MultiGpu.AMD
	GPU.MultipleSwapsDelta
	GPU.ProcessIntegrityResult
	GPU.ProcessLifetimeEvents.HardwareAccelerated
	Gaia.AuthFetcher.ListAccounts.NetErrorCodes
	Hardware.Display.Count.OnStartup
	Hardware.Display.SupportsHDR
	HeapProfiling.InProcess.Enabled
	Histogram.TooManyBuckets.1000
	History.DeleteFTSIndexDatabases
	History.DomainCount1Day_V2
	History.DomainCount28Day_V2
	History.DomainCount7Day_V2
	History.DomainCountQueryTime_V2
	History.FirstSetTopSitesDeltaSize
	History.FirstUpdateTime
	History.GetFavIconFromDB
	History.InMemoryDBItemCount
	History.InMemoryDBKeywordTermsCount
	History.InMemoryDBKeywordURLItemCount
	History.InMemoryURLHistoryItems
	History.InMemoryURLIndexingTime
	History.InMemoryURLIndexingTime.RoundTripTime
	History.InitTime
	ICU.CreateInstance
	ICU.DataFile
	Image.ResampleMS
	ImportantFile.FileReplaceRetryCount
	ImportantFile.SerializationDuration.Local_State
	ImportantFile.SerializationDuration.Preferences
	ImportantFile.SerializationDuration.Secure_Preferences
	InProductHelp.Config.ParsingEvent
	InfoBar.Shown
	LanguageDetection.TFLiteModel.WasModelAvailableForDetection
	LanguageDetection.TFLiteModel.WasModelRequestDeferred
	LanguageDetection.TFLiteModel.WasModelUnavailableDueToDeferredLoad
	LanguageUsage.AcceptLanguage
	LanguageUsage.AcceptLanguage.Count
	LanguageUsage.ApplicationLanguage
	Launch.Modes
	Layout.ScrollAnchor.SerializedAnchorSelectorLength
	Layout.ScrollAnchor.TimeToComputeAnchorNodeSelector
	LevelDB.ApproximateMemTableMemoryUse.CouponDatabase
	LevelDB.ApproximateMemTableMemoryUse.Metadata
	LevelDB.ApproximateMemTableMemoryUse.SharedProtoDB
	LevelDBEnv.DeleteTableBackupFile
	LibraryLoader.LoadNativeLibraryWindows
	LoadingPredictor.PreconnectCount
	LoadingPredictor.PreconnectHitsPercentage
	LoadingPredictor.PreresolveCount
	LoadingPredictor.PreresolveHitsPercentage
	MPArch.ChildProcessLaunchFirst
	MPArch.ChildProcessLaunchSubsequent
	MPArch.RPHCountPerLoad
	Media.Engagement.PreloadedList.CheckResult
	Media.MediaElement.ContentTypeParseable
	MediaRouter.Dial.AvailableDevicesCount
	MediaRouter.Dial.KnownDevicesCount
	MediaRouter.Ui.IconStateAtInit
	Memory.Experimental.Renderer.BlinkGC.DidFinishLoad
	Memory.Experimental.Renderer.BlinkGC.MainFrameDidFinishLoad
	Memory.Experimental.Renderer.Discardable.DidFinishLoad
	Memory.Experimental.Renderer.Discardable.MainFrameDidFinishLoad
	Memory.Experimental.Renderer.Malloc.DidFinishLoad
	Memory.Experimental.Renderer.Malloc.MainFrameDidFinishLoad
	Memory.Experimental.Renderer.NonDiscardableTotalAllocated.DidFinishLoad
	Memory.Experimental.Renderer.NonDiscardableTotalAllocated.MainFrameDidFinishLoad
	Memory.Experimental.Renderer.PartitionAlloc.DidFinishLoad
	Memory.Experimental.Renderer.PartitionAlloc.MainFrameDidFinishLoad
	Memory.Experimental.Renderer.TotalAllocated.DidFinishLoad
	Memory.Experimental.Renderer.TotalAllocated.MainFrameDidFinishLoad
	Memory.Experimental.Renderer.TotalAllocatedPerRenderView.DidFinishLoad
	Memory.Experimental.Renderer.TotalAllocatedPerRenderView.MainFrameDidFinishLoad
	Memory.Experimental.Renderer.V8MainThreadIsolate.DidFinishLoad
	Memory.Experimental.Renderer.V8MainThreadIsolate.MainFrameDidFinishLoad
	Memory.GPU.PeakMemoryAllocationSource2.PageLoad.SharedImageStub
	Memory.GPU.PeakMemoryUsage2.PageLoad
	NQE.ContentObserver.NetworkQualityMeaningfullyChanged
	NQE.RenderThreadNotified
	Navigation.BeginNavigationImpl.MainFrame
	Navigation.DidStartLoading.MainFrame
	Navigation.IsLockedProcess
	Navigation.IsLockedProcess.HTTPOrHTTPS
	Navigation.IsSameBrowsingInstance
	Navigation.IsSameProcess
	Navigation.IsSameProcess.NewNavigation
	Navigation.IsSameSiteInstance
	Navigation.IsSameSiteInstance.MainFrame
	Navigation.LoaderCreateToRequestStart.MainFrame
	Navigation.MainFrame.FrameCount
	Navigation.MainFrame.MaxFrameCount
	Navigation.MainFrame.SiteEngagementLevel
	Navigation.MainFrame.ThirdPartyCookieBlockingEnabled
	Navigation.MainFrameHasRTLDomain2
	Navigation.MainFrameHasRTLDomainDifferentPage2
	Navigation.MainFrameProfileType2
	Navigation.MainFrameScheme2
	Navigation.MainFrameSchemeDifferentPage2
	Navigation.OnBeforeUnloadBrowserToRendererIpcTime
	Navigation.OnBeforeUnloadOverheadTime
	Navigation.OriginAgentCluster.Result
	Navigation.QueueTime.OnReceiveResponse.MainFrame
	Navigation.QueueTime.OnStartLoadingResponseBody.MainFrame
	Navigation.ReadyToCommitUntilCommit2
	Navigation.ReadyToCommitUntilCommit2.ForegroundProcessPriority
	Navigation.ReadyToCommitUntilCommit2.NewNavigation
	Navigation.RendererCommitDelay.MainFrame
	Navigation.RendererCommitProcessWaitTime.MainFrame
	Navigation.RendererCommitQueueTime.MainFrame
	Navigation.RendererDidNavigateTime.MainFrame
	Navigation.RequiresDedicatedProcess
	Navigation.RequiresDedicatedProcess.HTTPOrHTTPS
	Navigation.SendCommitNavigationTime.MainFrame
	Navigation.StartToCommit
	Navigation.StartToCommit.CrossProcess
	Navigation.StartToCommit.CrossProcess.ForegroundProcessPriority
	Navigation.StartToCommit.CrossProcess.MainFrame
	Navigation.StartToCommit.CrossProcess.MainFrame.ForegroundProcessPriority
	Navigation.StartToCommit.CrossProcess.MainFrame.NewNavigation
	Navigation.StartToCommit.CrossProcess.NewNavigation
	Navigation.StartToCommit.ForegroundProcessPriority
	Navigation.StartToCommit.MainFrame
	Navigation.StartToCommit.MainFrame.ForegroundProcessPriority
	Navigation.StartToCommit.MainFrame.NewNavigation
	Navigation.StartToCommit.NewNavigation
	Navigation.StartToCommit.SameProcess
	Navigation.StartToCommit.SameProcess.ForegroundProcessPriority
	Navigation.StartToCommit.SameProcess.MainFrame
	Navigation.StartToCommit.SameProcess.MainFrame.ForegroundProcessPriority
	Navigation.StartToCommit.SameProcess.MainFrame.NewNavigation
	Navigation.StartToCommit.SameProcess.NewNavigation
	Navigation.ThrottleDeferTime.WillProcessResponse
	Navigation.ThrottleExecutionTime.WillProcessResponse
	Navigation.ThrottleExecutionTime.WillStartRequest
	Navigation.TimeToReadyToCommit2
	Navigation.TimeToReadyToCommit2.CrossProcess
	Navigation.TimeToReadyToCommit2.CrossProcess.NewNavigation
	Navigation.TimeToReadyToCommit2.MainFrame
	Navigation.TimeToReadyToCommit2.MainFrame.NewNavigation
	Navigation.TimeToReadyToCommit2.NewNavigation
	Navigation.TimeToReadyToCommit2.SameProcess
	Navigation.TimeToReadyToCommit2.SameProcess.NewNavigation
	Navigation.UserAgentStringType
	Navigation.WillStartRequestToLoaderStart.MainFrame
	NavigationSuggestion.GetDomainInfoDelayBeforeAllowingNavigation
	NavigationSuggestion.IsLookalikeUrlDelayBeforeAllowingNavigation
	NavigationSuggestion.PerformChecksDelayBeforeAllowingNavigation
	NavigationSuggestion.UpdateEngagedSitesDeferTime
	Net.Certificate.LeafExtendedKeyUsage.KnownRoot
	Net.Certificate.TrustAnchor.Verify
	Net.DNS.DnsConfig.SecureDnsMode
	Net.ErrorCodesForMainFrame4
	Net.HttpResponseCode
	Net.URLLoaderThrottleExecutionTime.BeforeWillProcessResponse
	Net.URLLoaderThrottleExecutionTime.WillProcessResponse
	Net.URLLoaderThrottleExecutionTime.WillStartRequest
	NetworkService.GrantSandboxResult
	NetworkService.GrantSandboxToCacheResult
	NetworkService.TimeToFirstResponse
	NetworkService.TimeToFirstResponse.OnStartup
	NetworkService.TimeToGrantCacheAccess
	NetworkService.TimeToGrantDataAccess
	NetworkService.TimeToMigrateData
	NetworkedProfile.Check
	Notifications.UsingSystemNotificationCenter
	Omnibox.PaintTime
	Omnibox.ProviderTime2.Bookmark
	Omnibox.ProviderTime2.Builtin
	Omnibox.ProviderTime2.Document
	Omnibox.ProviderTime2.HistoryQuick
	Omnibox.ProviderTime2.HistoryURL
	Omnibox.ProviderTime2.Keyword
	Omnibox.ProviderTime2.LocalHistoryZeroSuggest
	Omnibox.ProviderTime2.OnDeviceHead
	Omnibox.ProviderTime2.Search
	Omnibox.ProviderTime2.Shortcuts
	Omnibox.ProviderTime2.ZeroSuggest
	Omnibox.SearchPrefetch.PrefetchServingReason
	Omnibox.Start.WantAsyncMatches
	Omnibox.TabMatchTime
	Omnibox.ZeroSuggest.Eligible.OnFocusV2
	OptimizationGuide.HintCacheLevelDBStore.Status
	OptimizationGuide.RemoteFetchingEnabled
	PageActionController.ExtensionsWithPageActions
	PageLoad.Clients.Protocol.H2.DocumentTiming.NavigationToDOMContentLoadedEventFired
	PageLoad.Clients.Protocol.H2.DocumentTiming.NavigationToLoadEventFired
	PageLoad.Clients.Protocol.H2.PaintTiming.NavigationToFirstContentfulPaint
	PageLoad.Clients.Protocol.H2.PaintTiming.ParseStartToFirstContentfulPaint
	PageLoad.Clients.Protocol.H2.ParseTiming.NavigationToParseStart
	PageLoad.Clients.Scheme.HTTPS.PaintTiming.NavigationToFirstContentfulPaint
	PageLoad.Clients.Scheme.HTTPS.PaintTiming.ParseStartToFirstContentfulPaint
	PageLoad.Clients.Scheme.HTTPS.PaintTiming.UnderStat
	PageLoad.Clients.Scheme.HTTPS.PaintTiming.UnderStat.UserInitiated.NewNavigation
	PageLoad.Clients.Scheme.HTTPS.ParseTiming.NavigationToParseStart
	PageLoad.DocumentTiming.NavigationToDOMContentLoadedEventFired
	PageLoad.DocumentTiming.NavigationToLoadEventFired
	PageLoad.Experimental.PageTiming.CommitSentToFirstSubresourceLoadStart
	PageLoad.Experimental.PageTiming.NavigationToFirstSubresourceLoadStart
	PageLoad.Experimental.PageTiming.ResourceLoadTime.document
	PageLoad.Experimental.PageTiming.ResourceLoadTime.image
	PageLoad.Experimental.PageTiming.ResourceLoadTime.script
	PageLoad.Experimental.PageTiming.ResourceLoadTime.style
	PageLoad.Experimental.PageTiming.TotalSubresourceLoadTimeAtFirstContentfulPaint
	PageLoad.Experimental.PaintTiming.FirstEligibleToPaintToFirstPaint
	PageLoad.Experimental.PaintTiming.NavigationToFirstEligibleToPaint
	PageLoad.Internal.ErrorCode
	PageLoad.Internal.NavigationStartedInForeground
	PageLoad.Internal.PageLoadTimingStatus
	PageLoad.Internal.PageLoadTimingStatus.AtTimingCallbackDispatch
	PageLoad.Internal.PaintTiming.NavigationToFirstContentfulPaint.InitiatingProcess
	PageLoad.Internal.Renderer.PresentationTime.DeltaFromSwapTime
	PageLoad.Internal.Renderer.PresentationTime.Valid
	PageLoad.Navigation.RedirectChainLength
	PageLoad.PaintTiming.NavigationToFirstContentfulPaint
	PageLoad.PaintTiming.NavigationToFirstContentfulPaint.ByLiveTabCount.1Tab
	PageLoad.PaintTiming.NavigationToFirstContentfulPaint.LoadType.NewNavigation
	PageLoad.PaintTiming.NavigationToFirstContentfulPaint.UserInitiated
	PageLoad.PaintTiming.NavigationToFirstImagePaint
	PageLoad.PaintTiming.NavigationToFirstPaint
	PageLoad.PaintTiming.ParseStartToFirstContentfulPaint
	PageLoad.ParseTiming.NavigationToParseStart
	PageLoad.ParseTiming.NavigationToParseStart.LoadType.NewNavigation
	PageLoad.ParseTiming.ParseBlockedOnScriptExecution
	PageLoad.ParseTiming.ParseBlockedOnScriptExecutionFromDocumentWrite
	PageLoad.ParseTiming.ParseBlockedOnScriptLoad
	PageLoad.ParseTiming.ParseBlockedOnScriptLoadFromDocumentWrite
	PageLoad.ParseTiming.ParseDuration
	PaintHolding.InputTiming2
	PasswordManager.LoginDatabaseInit
	PasswordManager.PasswordStoreInitResult
	PasswordManager.SyncMetadataReadError
	PerformanceManager.FrameSiteInstanceProcessRelationship.ByProcess2
	PerformanceManager.FrameSiteInstanceProcessRelationship.ByTime2
	PerformanceManager.FramesPerRendererByTime
	PerformanceManager.SiteInstancesPerRendererByTime
	Permissions.QuietNotificationPrompts.IsEnabledInPrefs
	Platform.IntelMaxMicroArchitecture
	Platform.LogicalCpuCount
	Power.FrameDamageAreaInDip.Browser
	Power.FrameDamageAreaInDip.Renderer
	Power.FrameDamageDiagonalInDip.Browser
	Power.FrameDamageDiagonalInDip.Renderer
	PrefService.ReadError
	Privacy.CookieControlsSetting
	Privacy.DoNotTrackSetting
	Privacy.ThirdPartyCookieBlockingSetting
	PrivacyBudget.Identifiability.FinchConfigValidationResult
	Profile.AllAccounts.Categories
	Profile.AllAccounts.Names
	Profile.BrowserActive.PerProfile
	Profile.NumberOfAccountsPerProfile
	Profile.NumberOfProfiles
	Profile.State.Avatar_All
	Profile.State.Avatar_SingleProfile
	Profile.State.LastUsed_All
	Profile.State.LastUsed_SingleProfile
	Profile.State.Name_All
	Profile.State.Name_SingleProfile
	Profile.State.SyncEnabled_All
	Profile.State.SyncEnabled_SingleProfile
	Profile.State.UnconsentedPrimaryAccountType_All
	Profile.State.UnconsentedPrimaryAccountType_SingleProfile
	Profile.TriggeredReset
	Profile.UserAction.PerProfile
	ProtoDB.GetErrorStatus.Metadata
	ProtoDB.GetFound.Metadata
	ProtoDB.GetSuccess.Metadata
	ProtoDB.InitStatus.CouponDatabase
	ProtoDB.InitStatus.Metadata
	ProtoDB.InitStatus.SharedDb
	ProtoDB.LoadEntriesSuccess.Default
	ProtoDB.SharedDbInitStatus
	ProtoDB.UpdateErrorStatus.Metadata
	ProtoDB.UpdateSuccess.Metadata
	ReadingList.Read.Count.OnModelLoaded
	ReadingList.SyncStateMatchesBookmarks
	ReadingList.Unread.Count.OnModelLoaded
	RenderTextHarfBuzz.ShapeRunsFallback
	Renderer.BrowserLaunchToRunLoopStart
	Renderer.Font.PrimaryFont.DomContentLoaded
	Renderer.Font.PrimaryFont.DomContentLoaded.Style
	Renderer.Font.Shaping.DomContentLoaded
	Renderer.Font.SystemFallback.DomContentLoaded
	Renderer.ProcessLifetime2.HighResolution
	Renderer.ProcessLifetime2.LowResolution
	Renderer.RenderThreadImpl.Init
	Renderer.TotalCPUUse2
	Renderer.TotalCPUUse2.ShortLived
	Renderer4.GpuRasterizationEnabled
	RendererScheduler.RendererMainThreadLoad5
	RendererScheduler.RendererMainThreadLoad5.Foreground
	RendererScheduler.TaskTime2
	RendererScheduler.WebFramesPerScheduler
	RendererScheduler.WebViewsPerScheduler
	ResourceCoordinator.LocalDB.DatabaseInit
	SBIRS.DroppedIncident
	SBIRS.ReceivedIncident
	SafeBrowsing.BrowserThrottle.IsCheckCompletedOnProcessResponse
	SafeBrowsing.FileTypeUpdate.ResourceBundleResult
	SafeBrowsing.FileTypeUpdate.ResourceBundleVersion
	SafeBrowsing.HasCookieAtStartup
	SafeBrowsing.MetricsCollector.IsPrefValid
	SafeBrowsing.Pref.Daily.Extended
	SafeBrowsing.Pref.Daily.SafeBrowsingModeManaged
	SafeBrowsing.Pref.Daily.SafeBrowsingState
	SafeBrowsing.Pref.Enhanced
	SafeBrowsing.Pref.Extended
	SafeBrowsing.Pref.General
	SafeBrowsing.V4Store.OldFileNameExists.UrlCsdDownloadWhitelist
	SafeBrowsing.V4Store.OldFileNameExists.UrlCsdWhitelist
	SafeBrowsing.V4Store.OldFileNameInUse.UrlCsdDownloadWhitelist
	SafeBrowsing.V4Store.OldFileNameInUse.UrlCsdWhitelist
	Scheduler.CancelableTaskTracker.TaskDuration2_CanceledBackgroundOffSequence
	Scheduler.CancelableTaskTracker.TaskDuration2_CanceledBackgroundSameSequence
	Scheduler.CancelableTaskTracker.TaskDuration2_CanceledForegroundOffSequence
	Scheduler.CancelableTaskTracker.TaskDuration2_CanceledForegroundSameSequence
	Scheduler.CancelableTaskTracker.TaskDuration2_LiveBackgroundOffSequence
	Scheduler.CancelableTaskTracker.TaskDuration2_LiveBackgroundSameSequence
	Scheduler.CancelableTaskTracker.TaskDuration2_LiveForegroundOffSequence
	Scheduler.CancelableTaskTracker.TaskDuration2_LiveForegroundSameSequence
	Scheduler.CancelableTaskTracker.TaskStatus
	Scheduling.Browser.BeginImplFrameLatency2
	Scheduling.Browser.CommitToReadyToActivateDuration2
	Scheduling.Browser.CommitToReadyToActivateDuration2.Same
	Scheduling.Browser.DrawDuration2
	Scheduling.Renderer.BeginImplFrameLatency2
	Scheduling.Renderer.CommitToReadyToActivateDuration2
	Scheduling.Renderer.CommitToReadyToActivateDuration2.Same
	Scheduling.Renderer.DeadlineMode
	Scheduling.Renderer.DrawDuration2
	Scheduling.Renderer.DrawInterval2
	Scheduling.Renderer.FrameProduction.TimeOverused
	Scheduling.Renderer.FrameProduction.TimeUnused
	Search.DefaultSearchChangeOrigin
	Search.DefaultSearchProviderType
	Security.HttpsFirstMode.SettingEnabledAtStartup
	Security.JSONParser.ChromiumExtensionUsage
	Security.SafetyTips.GetDomainInfoTime
	Security.SafetyTips.GetReputationStatusWithEngagedSitesTime
	Security.SafetyTips.ReputationCheckComplete.DidFinishNavigation
	Security.SafetyTips.SafetyTipShown
	Security.SafetyTips.StatusWithInitiator.Unknown
	Security.SecurityLevel.OnCommit
	ServiceWorker.OnBrowserStartup.SkipServiceWorkerOnFirstNavigation
	ServiceWorker.RegisteredStorageKeyCount
	ServiceWorker.Storage.ReadInitialDataFromDB.Time
	ServiceWorker.Storage.RegisteredStorageKeyCacheInitialization.Time
	Settings.AdvancedSpellcheck.OnStartup
	Settings.AutocompleteSearches.OnStartup
	Settings.FilterOnLoadTime
	Settings.FilterSerializeDataTime
	Settings.JsonDataReadSizeKilobytes.Local_State
	Settings.JsonDataReadSizeKilobytes.Preferences
	Settings.PreloadStatus.OnStartup
	Settings.PrivacySandbox.Enabled
	Settings.ShowHomeButton
	Settings.StartupPageLoadSettings
	Settings.TrackedPreferenceCleared.FromRegistry
	Settings.TrackedPreferenceNullInitialized
	Settings.TrackedPreferenceUnchanged
	Settings.TrackedPreferenceUnchanged.FromRegistry
	Settings.TrackedPreferencesNoEnforcementOnDomain
	SharedMemory.MapBlockedForSecurity
	Shutdown.ShutdownType
	Signin.AccountTracker.CountOfLoadedAccounts
	Signin.AccountTracker.GaiaIdMigrationState
	Signin.CookieJar.SignedInCount_OnChange
	Signin.CookieJar.SignedOutCount_OnChange
	Signin.CookieJar.StableAge_OnChange
	Signin.CookieJar.TotalCount_OnChange
	Signin.IsShared_OnChange
	Signin.ListAccountsFailure
	Signin.Reconciler.Duration.UpTo3mins.Success
	Signin.Reconciler.Operation
	Signin.Reconciler.Trigger.Noop
	Signin.SigninAllowed
	Signin.TokenTable.GetAllTokensSqlStatementValidity
	SimpleCache.Code.CacheSizeOnInit
	SimpleCache.Code.ConsistencyResult
	SimpleCache.Code.CreationToIndex
	SimpleCache.Code.DiskCloseLatency
	SimpleCache.Code.DiskCreateLatency
	SimpleCache.Code.EntryCreationTime
	SimpleCache.Code.HeaderSize
	SimpleCache.Code.IndexCreatedEntryCount
	SimpleCache.Code.IndexInitializeMethod
	SimpleCache.Code.IndexNumEntriesOnInit
	SimpleCache.Code.IndexRestoreTime
	SimpleCache.Code.MaxCacheSizeOnInit
	SimpleCache.Code.OpenEntryIndexState
	SimpleCache.Code.SyncCloseResult
	SiteEngagementService.EngagementType
	SiteIsolatedCodeCache.JS.Behaviour
	SiteIsolation.BrowsingInstance.MaxCountPerProcess
	SpellCheck.CheckedWords
	SpellCheck.CustomWords
	SpellCheck.Enabled
	SpellCheck.MisspelledWords
	SpellCheck.ReplacedWords
	SpellCheck.ShownSuggestions
	SpellCheck.SpellingService.Enabled
	Spellcheck.Windows.ChromeLocalesSupport.Both
	Spellcheck.Windows.ChromeLocalesSupport.HunspellOnly
	Spellcheck.Windows.ChromeLocalesSupport.NativeOnly
	Spellcheck.Windows.ChromeLocalesSupport.NoSupport
	Spellcheck.Windows.SpellcheckLocalesSupport.Both
	Spellcheck.Windows.SpellcheckLocalesSupport.HunspellOnly
	Spellcheck.Windows.SpellcheckLocalesSupport.NativeOnly
	Stability.Counts2
	Stability.Experimental.PageLoads
	StackSamplingProfiler.MetadataSlotsUsed
	Startup.BrowserMainRunnerImplInitializeLongTime
	Startup.BrowserMainRunnerImplInitializeStep1Time
	Startup.BrowserMainRunnerImplInitializeStep2Time
	Startup.BrowserMessageLoopFirstIdle
	Startup.BrowserMessageLoopFirstIdle.WarmStartup
	Startup.BrowserMessageLoopStart.To.NonEmptyPaint2
	Startup.BrowserMessageLoopStart.To.NonEmptyPaint2.WarmStartup
	Startup.BrowserMessageLoopStartHardFaultCount
	Startup.BrowserMessageLoopStartTime
	Startup.BrowserMessageLoopStartTime.WarmStartup
	Startup.BrowserProcessImpl_PreMainMessageLoopRunTime
	Startup.BrowserWindow.FirstPaint
	Startup.BrowserWindow.FirstPaint.WarmStartup
	Startup.BrowserWindowDisplay
	Startup.BrowserWindowDisplay.WarmStartup
	Startup.CreateFirstProfile
	Startup.DoUpgradeTasks.NoRelaunch
	Startup.FirstWebContents.FinishReason
	Startup.FirstWebContents.MainNavigationFinished
	Startup.FirstWebContents.MainNavigationFinished.WarmStartup
	Startup.FirstWebContents.MainNavigationStart
	Startup.FirstWebContents.MainNavigationStart.WarmStartup
	Startup.FirstWebContents.NonEmptyPaint3
	Startup.FirstWebContents.NonEmptyPaint3.NoMemoryPressure
	Startup.FirstWebContents.NonEmptyPaint3.WarmStartup
	Startup.FirstWebContents.RenderProcessHostInit.ToNonEmptyPaint
	Startup.FirstWebContents.RenderProcessHostInit.ToNonEmptyPaint.WarmStartup
	Startup.IncognitoForcedStart
	Startup.LoadTime.ApplicationStartToChromeMain
	Startup.LoadTime.ApplicationStartToChromeMain.WarmStartup
	Startup.LoadTime.ProcessCreateToApplicationStart
	Startup.LoadTime.ProcessCreateToApplicationStart.WarmStartup
	Startup.PreMainMessageLoopRunImplLongTime
	Startup.StartupBrowserCreator_Start
	Startup.Temperature
	Style.RebuildLayoutTreeTime
	Style.RecalcTime
	SubresourceFilter.PageLoad.ActivationDecision
	SubresourceFilter.PageLoad.ActivationList
	SubresourceFilter.PageLoad.ActivationState
	SubresourceFilter.PageLoad.SafeBrowsingDelay
	SubresourceFilter.RulesetVerificationStatus
	SubresourceFilter.SafeBrowsing.TotalCheckTime
	Sync.ModelTypeStoreBackendError.ReadRecords
	Tab.TabUnderAction
	TabGroups.CollapsedGroupCountPerLoad
	TabGroups.UserCustomizedGroupCountPerLoad
	TabGroups.UserGroupCountPerLoad
	Tabs.ActiveTabWidth
	Tabs.InactiveTabWidth
	Tabs.MaxTabsInADay
	Tabs.MaxTabsInADay.PluggedIn
	Tabs.MaxTabsPerWindowInADay
	Tabs.MaxTabsPerWindowInADay.PluggedIn
	Tabs.MaxWindowsInADay
	Tabs.MaxWindowsInADay.PluggedIn
	Tabs.TabCountActiveWindow
	Tabs.TabCountInGroupPerLoad
	Tabs.TabCountPerDomainPerLoad.0to5
	Tabs.TabCountPerLoad
	Tabs.TabCountPerWindow
	Tabs.TabsStatsDailyEventInterval
	ThreadPool.NumTasksBeforeDetach.Browser.Background
	ThreadPool.NumTasksBeforeDetach.Browser.Foreground
	Touchscreen.TouchEventsEnabled
	Translate.ApplicationStart.AlwaysTranslateLanguage.Count
	Translate.ApplicationStart.NeverTranslateLanguage
	Translate.ApplicationStart.NeverTranslateLanguage.Count
	Translate.ApplicationStart.NeverTranslateSite.Count
	Translate.CaptureText
	Translate.InitiationStatus.v2
	Translate.LanguageDetection.ContentLength
	Translate.LanguageDeterminedDuration
	Translate.TargetLanguage.Origin
	UI.DeviceScale
	UKM.Entries.Dropped
	UKM.Entries.Dropped.ByEntryHash
	UKM.PersistentLogRecall.Status
	UKM.Sources.Dropped
	UMA.CleanExitBeaconConsistency2
	UMA.EntropySourceType
	UMA.LowEntropySource3Value
	UMA.MetricsService.Initialize.Time
	UMA.PersistentAllocator.BrowserMetrics.Errors
	UMA.PersistentAllocator.BrowserMetrics.UsedPct
	UMA.PersistentAllocator.FieldTrialAllocator.Errors
	UMA.PersistentAllocator.FieldTrialAllocator.UsedPct
	UMA.PersistentAllocator.RendererMetrics.Errors
	UMA.PersistentAllocator.RendererMetrics.UsedPct
	UMA.PersistentHistograms.InitResult
	UnifiedConsent.MakeSearchesAndBrowsingBetter.OnStartup
	V8.CompileLazyMicroSeconds
	V8.CompileMicroSeconds
	V8.CompileScript.CacheBehaviour
	V8.CompileScriptMicroSeconds
	V8.CompileScriptMicroSeconds.IsolateCacheHit
	V8.CompileScriptMicroSeconds.NoCache.Other
	V8.ErrorsThrownPerContext
	Variations.Headers.ExperimentCount
	Variations.Headers.RequestContextCategory
	Variations.Headers.URLValidationResult.Append
	Variations.LoadPermanentConsistencyCountryResult
	Variations.PolicyRestriction
	Variations.ResourceRequestsAllowed
	Variations.SafeMode.Streak.Crashes
	Variations.SafeMode.Streak.FetchFailures
	Variations.SeedLoadResult
	Variations.SeedUsage
	Variations.UserChannel
	WebApp.Engagement.NoUserInstalledApps
	WebApp.Preinstalled.AppDuplicationFixApplied
	WebApp.Preinstalled.MigratingWebAppAbsentChromeAppAbsent
	WebApp.Preinstalled.MigratingWebAppAbsentChromeAppPresent
	WebApp.Preinstalled.MigratingWebAppPresentChromeAppAbsent
	WebApp.Preinstalled.MigratingWebAppPresentChromeAppPresent
	WebApp.Uninstall.NonSyncIncompleteCount
	WebContentsObserver.DOMContentLoaded
	WebContentsObserver.DidChangeVisibleSecurityState
	WebContentsObserver.DidFinishLoad
	WebContentsObserver.DidFinishNavigation
	WebContentsObserver.DidFirstVisuallyNonEmptyPaint
	WebContentsObserver.DidStartLoading
	WebContentsObserver.DidStartNavigation
	WebContentsObserver.DidStopLoading
	WebContentsObserver.LoadProgressChanged
	WebContentsObserver.NavigationEntryChanged
	WebContentsObserver.NavigationEntryCommitted
	WebContentsObserver.OnVisibilityChanged
	WebContentsObserver.PrimaryMainDocumentElementAvailable
	WebContentsObserver.RenderFrameCreated
	WebContentsObserver.RenderFrameDeleted
	WebContentsObserver.RenderViewReady
	WebContentsObserver.TitleWasSet
	Webapp.SystemApps.FreshInstallDuration
	WindowManager.AppWindowCountPerLoad
	WindowManager.PopUpWindowCountPerLoad
	WindowManager.TabbedWindowCountPerLoad
	Windows.ChromeDllPrefetchResult
	Windows.FileDeleteRetryCount

*/